- name: Create_Snapshots
  hosts: hosts

  tasks:
   - name: Create Snapshots
     ansible.windows.win_shell: |
      $VMs = Get-VM
      $VMs | ForEach-Object -Process {
          if ($_.State -eq "Running") {
              try {
                  Checkpoint-VM -Name $_.Name -SnapshotName "Ansible_Snapshot"
                  Write-Host "Checkpoint created successfully for VM: $($_.Name)"
              } catch {
                  Write-Host "Failed to create checkpoint for VM: $($_.Name). Error: $($_.Exception.Message)" -ForegroundColor Red
              }
          }
      }