- name: Domain Join
  hosts: hosts

  tasks:
    - name: Join a domain
      ansible.windows.win_domain_membership:
        dns_domain_name: "vmhomelab.local"
        hostname: "{{ Server_Name }}"
        domain_admin_user: "administrator"
        domain_admin_password: "{{ Domain_Pwd }}"
        ou_path: "OU=Server,OU=vmhomelab,DC=vmhomelab,DC=local"
        state: domain
      register: domain_state

    - name: Reboot host after domain join
      ansible.windows.win_reboot:
      when: domain_state.reboot_required

    - name: Wait until the VM responds to ping 5 times
      ansible.windows.win_shell: |
        Start-Sleep -Seconds 5
        $PingCount = 0

        $VMName = "{{ Server_Name }}"

        # Start the ping test
        while ($PingCount -lt 5) {
            
            Write-Host "Pinging Server: $VMName"

            # Ping the IP address
            $pingResult = Test-Connection -ComputerName $VMName -Count 1 -Quiet
            if ($pingResult) {
                $PingCount++
                Write-Host "$VMName responded to ping ($PingCount/5)"
            } else {
                $PingCount = 0
                Write-Host "$VMName did not respond, resetting count"
            }
            Start-Sleep -Seconds 5
        }
      register: ping_result

    - name: Execute PowerShell script after VM is responding
      ansible.windows.win_shell: |
        Write-Host 'Executing PowerShell script after successful ping...'
        & "C:\temp\Send_Telegram_Message_After_VM_Reboot.ps1"
        Write-Host 'PowerShell script executed.'
      when: ping_result is success      
