---
- hosts: windows
  tasks:

  - name: Run PowerShell script that modifies the module changed result
    ansible.windows.win_powershell:
      script: |
        if (Get-Service -Name test -ErrorAction SilentlyContinue) {
            Remove-Service -Name test
        }
        else {
            $Ansible.Changed = $false
        }

  - name: Run a script
    win_shell: C:\temp\test.ps1