---
- hosts: windows
  become: false
  gather_facts: false
  vars:
    ansible_remote_tmp: C:/Windows/Temp/ansible

  tasks:

  - name: Extract PS output.
    shell: 
      cmd: "C:\\test.ps1"
    register: pmon

  - name: Display PS output.
    debug:
      msg: "{{ pmon.stdout_lines }}"


