---
# This playbook runs a basic DF command.

- hosts: windows
  #remote_user: root

  tasks:
  - name: Run a PowerShell script with -NoProfile
  ansible.windows.win_shell: C:\somescript.ps1
  args:
    no_profile: true

