---
- hosts: windows
  tasks:

  - name: Run PowerShell script that modifies the module changed result
    ansible.windows.win_powershell: C:\temp\test.ps1

  - name: Run a script
    win_shell: C:\temp\test.ps1