- name: Reboot VM
  hosts: hosts
  remote_user: svc_ansible
  
  tasks:
  - name: Reboot
    ansible.windows.win_shell: |
      $VMName = "{{ Server_Name }}"
      try {
        # Reboot the computer
        Restart-VM -Name $VMName -Force -ErrorAction Stop
        Write-Host "The VM '$VMName' is being rebooted." -ForegroundColor Green
      } catch {
          # Handle any errors that occur during the reboot process
          Write-Host "Failed to reboot the computer '$VMName'. Error: $($_.Exception.Message)" -ForegroundColor Red
      }
      