- name: Reboot VM
  hosts: hosts
  remote_user: svc_ansible
  
  tasks:
    - name: Rename VM
      ansible.windows.win_shell: |
        $username = "svc_ansible"
        $password = "rDKx.sv5Yz&NK~x&ziuz9KyT`%xgPS"
        $credential = New-Object System.Management.Automation.PSCredential($username, $password)
        Invoke-Command -VMName "{{VM_Name}}" -Credential $credential -ScriptBlock { Rename-Computer -NewName "{{NewComputerName}}" }