- name: Reboot VM
  hosts: hosts
  remote_user: svc_ansible
  
  tasks:
    - name: Rename VM
      ansible.windows.win_shell: |
        Invoke-Command -VMName "{{VM_Name}}" -ScriptBlock { Rename-Computer -NewName "{{NewComputerName}}" }