- name: Reboot VM
  hosts: hosts
  remote_user: svc_ansible
  
  tasks:
    - name: Rename VM
      ansible.windows.win_shell: |
        $VMName = "VMH-AutomatedVM-SRV"
        $NewComputerName = "VMH-AutomatedVM-SRV"
        $username = "svc_ansible"
        $password = "{{ Password }}"
        $userPassword = ConvertTo-SecureString -String $password -AsPlainText -Force
        $userCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $userPassword

        Invoke-Command -VMName $VMName -Credential $userCredential -ScriptBlock {
            param($NewComputerName)
            Rename-Computer -NewName $NewComputerName -Force
        } -ArgumentList $NewComputerName