---
- hosts: windows_server
  become: false
  gather_facts: false


  tasks:

  - name: Install all critical and security updates
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      state: installed
    register: update_result