- name: Default Setup
  hosts: hv01vms
  
  tasks:
    - name: Install all security, critical, and rollup updates without a scheduled task
      ansible.windows.win_updates:
        reboot: yes
        reboot_timeout: 600
        reject_list:
          - KB5034439
        category_names: '*'
      become: true
      become_method: runas
      become_user: SYSTEM